### PR TITLE
removable items / milestones

### PR DESCRIPTION
**Pull request by PluharVit**
#54

### CODE REVIEW

**Comment by LaChope** [comment]
Did you commit everything? It does not work on the deploy here

image


Even when I create new task, it does not work

image

**Comment by PluharVit** [comment]
What do you mean? I don't see anything wrong.

**Comment by LaChope** [comment]
When I am using the deploy preview (https://deploy-preview-75--react-maintenance-planner.netlify.app/), I do not see any delete option (as shown on screenshots above). I tried on existing tasks, and I also created new task and still couldn't see any delete icon

**Comment by PluharVit** [comment]
Both screenshots you shared are creating task. The delete button is displayed only in editing modal. Using the link you sent, it works fine for me, see bellow. 


obrazek

**Comment by LaChope** [comment]
How do I get the editing modal then? I was double clicking on the task.

**Comment by PluharVit** [comment]
Just click on the edit icon.

**Comment by LaChope** [comment]
Ooooh ok I get it now. I thought we want to completely get rid of these icons and that everything would be handled with the modal, can you make this modification?

**Comment by PluharVit** [comment]
Yeah, okey, I'll look at it.

**Comment by LaChope** [comment]
That's great, LGTM

**Pull request merged**
