### PR TITLE
Remove resources from tree

### PR DESCRIPTION
**Pull request by LaChope**
Related to https://github.com/kbss-cvut/csat-maintenance-planner/issues/25#issue-1256349981

### CODE REVIEW

**Comment by blcham** [comment]
@LaChope remove works nicely, 

- just quite a dangerous operation that is done very easily so I was wondering why undo-redo buttons are not working in the preview (Were they supposed to work?)

**Comment by blcham** [comment]
I would do for now undo-redo only, and wait what MK says about it ... To me best solution would be similar as it is in gmail.

1) whenever you do action there is message showing that you did it
2) you can redo it very easily using "Undo" link

image


However, i still believe this is only in category just "nice to have" ... and we have many "must"s probably

**Comment by blcham** [comment]
So to summarize I would add ticket to solve undo-redo.

**Comment by LaChope** [comment]
@blcham @PluharVit I assume I can merge this PR and create new issue for undo/redo ?

**Comment by blcham** [comment]
I agree.

**Pull request closed without merging**
